[package]
name = "ant-book-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"

[[bin]]
name = "1-1a"
path = "src/bin/1-1a-kujibiki.rs"

[[bin]]
name = "1-6a"
path = "src/bin/1-6a-triangle.rs"

[[bin]]
name = "1-6b"
path = "src/bin/1-6b-ants.rs"

[[bin]]
name = "1-6c"
path = "src/bin/1-6c-kujibiki.rs"

[[bin]]
name = "2-1a"
path = "src/bin/2-1a-bubunwa.rs"

[[bin]]
name = "2-1b"
path = "src/bin/2-1b-lake-counting.rs"

[[bin]]
name = "2-1c"
path = "src/bin/2-1c-maze.rs"

[[bin]]
name = "2-2a"
path = "src/bin/2-2a-coin.rs"

[[bin]]
name = "2-2b"
path = "src/bin/2-2b-kukan-scheduling.rs"

[[bin]]
name = "2-2c"
path = "src/bin/2-2c-best-cow-line.rs"

[[bin]]
name = "2-2d"
path = "src/bin/2-2d-saruans-army.rs"

[[bin]]
name = "2-2e"
path = "src/bin/2-2e-fence-repair.rs"

[[bin]]
name = "2-3a"
path = "src/bin/2-3a-knapsack.rs"
