[package]
name = "ant-book-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"

[[bin]]
name = "1-1a"
path = "src/bin/1-1a-kujibiki.rs"
